<div class="container">
    <!-- Navigation Menu -->
    <nav class="nav-menu">
        <a href="{{ var: $url['defaultUrl'] }}">Home</a>
        <a href="{{ var: $url['logoutUrl'] }}">Logout</a>
    </nav>

    <div class="form-box">
        <h2>2FA Verification</h2>
        <p class="form-description">Two-factor authentication (2FA) has been requested. To continue, please scan the QR code in your authenticator app (e.g., Google Authenticator) and enter the 6-digit code generated by the app to confirm your setup.</p>
        <div class="qr-code">
            <img src="{{ var: $qrIMG }}" alt="2FA QR Code" class="qr-image">
        </div>
        <span class="user-icon">
            <div class="icon-wrapper">
                <svg width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="#ffffff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                    <rect x="3" y="11" width="18" height="11" rx="2" ry="2"></rect>
                    <path d="M7 11V7a5 5 0 0 1 10 0v4"></path>
                    <path d="M10 16l2 2 4-4"></path>
                </svg>
            </div>
        </span>
        <form id="twofaform" method="POST">
            <div class="form-group">
                <label for="two-fa">Enter 6-digit code</label>
                <div class="two-fa-inputs">
                    <input type="text" maxlength="1" placeholder="-" id="first">
                    <input type="text" maxlength="1" placeholder="-">
                    <input type="text" maxlength="1" placeholder="-">
                    <input type="text" maxlength="1" placeholder="-">
                    <input type="text" maxlength="1" placeholder="-">
                    <input type="text" maxlength="1" placeholder="-">
                </div>
            </div>
			{{ formName(ConfirmAuthCode) }}
            <input type="hidden" name="code" value="">
			<div class="error-message" id="error-message"></div>
            <div class="btn" id="confirm2fa">Confirm</div>			
        </form>
    </div>
</div>